# For info on how to configure this image:
# read https://hub.docker.com/_/mysql
version: '3.3'

services:
  mysql:
    image: mysql:8
    container_name: parker-mysql
    restart: always

    # mysql 8 uses the new 'caching_sha2_password' auth plugin by default
    # our database driver - mysql2 - doesn't support 'caching_sha2_password'
    # so we roll back to the good old 'mysql_native_password' auth plugin
    # like so:
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass123'
      MYSQL_DATABASE: 'parker'
    ports:
      - 3306:3306
    logging:
      driver: json-file
    volumes:
      - parker-mysql-db:/var/lib/mysql

  parker:
    image: localhost:5000/parker-app
    container_name: parker-app
    links:
      - mysql
    logging:
      driver: json-file
    ports:
      - 3000:3000

  apache:
    image: localhost:5000/parker-apache
    container_name: parker-apache
    links:
      - parker
    logging:
      driver: json-file
    ports:
      - 80:80
      - 443:443

volumes:
  parker-mysql-db:
